name: check secret

# Definiamo quando questa cosa cominerà a funzionare:
on:
  push:
    branches:
      - main

# definiamo quello che dovrà fare
jobs:
  check-secret-job:
  # Qui si può usar eil linguaggio che si vuole usare
  runs-on: ubuntu-latest
  steps:
    - name: check_secret_step
    # Definiamo le variabili d'ambiente
      env: 
        MY_FIRST_SECRET_NAME_ENV: ${{secrets.MY_FIRST_SECRET_NAME}}
      run: echo "Il mio primo segreto": ${{secrets.MY_FIRST_SECRET_NAME}}  # analogo di print in python